# Jekyll Configuration for Specifys.ai Blog
# GitHub Pages compatible setup

# Site settings
title: "Specifys.ai"
description: "AI-powered app planning platform - Generate specifications, discover development tools, and plan your app smarter with AI-driven insights"
url: "https://specifys-ai.com"
baseurl: ""
author: "Specifys.ai"
keywords: "AI development tools, app specification generator, no-code platform, AI-powered planning, vibe coding"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

# Collections
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins (GitHub Pages compatible)
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata
  - .gitignore
  - .git
  - .DS_Store
  - Thumbs.db
  - package.json
  - package-lock.json
  - create-post.js
  - create-post.sh
  - create-post.bat
  - config/

# Include files
include:
  - _redirects

# Sass settings
sass:
  sass_dir: assets/css
  style: compressed

# Kramdown settings
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false

# SEO settings
lang: en
locale: en_US
timezone: America/New_York

# Social links
twitter:
  username: specifysai
linkedin:
  url: https://www.linkedin.com/company/specifys-ai/

# Google Analytics
google_analytics: G-RWBT69JCM7

