const express = require('express');
// Use built-in fetch for Node.js 18+ or fallback to node-fetch
let fetch;
if (typeof globalThis.fetch === 'function') {
  // Node.js 18+ has built-in fetch (used in Render)
  fetch = globalThis.fetch;
} else {
  // Fallback for older Node versions
  fetch = require('node-fetch');
}
const dotenv = require('dotenv');
const config = require('./config');

dotenv.config();

const app = express();
const port = config.port;

// Middleware to parse JSON bodies
app.use(express.json());

// CORS middleware to allow requests from your frontend
app.use((req, res, next) => {
  const origin = req.headers.origin;
  
  // Check if origin is in allowed list
  if (origin && config.allowedOrigins.includes(origin)) {
    res.header('Access-Control-Allow-Origin', origin);
  } else {
    res.header('Access-Control-Allow-Origin', '*'); // Fallback for development
  }
  
  res.header('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept, Authorization');
  res.header('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS');
  
  // Handle preflight requests
  if (req.method === 'OPTIONS') {
    res.sendStatus(200);
  } else {
    next();
  }
});

// Feedback endpoint
app.post('/api/feedback', async (req, res) => {
  const { email, feedback, type, source } = req.body;

  if (!feedback) {
    return res.status(400).json({ error: 'Feedback text is required' });
  }

  try {
    // 1. Send email notification
    await sendFeedbackEmail(email, feedback);
    
    // 2. Save to Google Sheets via Google Apps Script
    await saveToGoogleSheets(email, feedback, type, source);
    
    res.json({ success: true, message: 'Feedback submitted successfully' });
  } catch (error) {

    res.status(500).json({ error: 'Failed to process feedback' });
  }
});

// Function to send feedback email
async function sendFeedbackEmail(email, feedback) {
  try {
    // Check if email configuration is available
    const emailUser = process.env.EMAIL_USER;
    const emailPassword = process.env.EMAIL_APP_PASSWORD;
    const feedbackEmail = process.env.FEEDBACK_EMAIL;
    
    if (emailUser && emailPassword && feedbackEmail) {
      // Use Nodemailer to send email
      const nodemailer = require('nodemailer');
      
      const transporter = nodemailer.createTransporter({
        service: 'gmail',
        auth: {
          user: emailUser,
          pass: emailPassword
        }
      });
      
      const mailOptions = {
        from: emailUser,
        to: feedbackEmail,
        subject: 'New Feedback from Specifys.ai',
        html: `
          <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
            <h2 style="color: #0078d4;">📝 New Feedback Received</h2>
            <div style="background: #f5f5f5; padding: 20px; border-radius: 8px; margin: 20px 0;">
              <p><strong>📧 User Email:</strong> ${email || 'Not provided'}</p>
              <p><strong>🕒 Time:</strong> ${new Date().toLocaleString('he-IL', { timeZone: 'Asia/Jerusalem' })}</p>
              <p><strong>📱 Source:</strong> Specifys.ai Try Page</p>
            </div>
            <div style="background: #fff; padding: 20px; border-left: 4px solid #0078d4; margin: 20px 0;">
              <h3 style="color: #333; margin-top: 0;">Feedback Content:</h3>
              <p style="color: #555; line-height: 1.6; white-space: pre-wrap;">${feedback}</p>
            </div>
            <hr style="border: none; border-top: 1px solid #eee; margin: 20px 0;">
            <p style="color: #666; font-size: 12px;">This email was automatically generated by the Specifys.ai feedback system.</p>
          </div>
        `
      };
      
      const info = await transporter.sendMail(mailOptions);
      
    } else {
      // Fallback: log to console
    }
    
  } catch (error) {

    // Don't fail the entire request if email fails
  }
}

// Function to save feedback to Google Sheets via Google Apps Script
async function saveToGoogleSheets(email, feedback, type, source) {
  try {
    // Use the Google Apps Script URL from config
    const googleAppsScriptUrl = config.googleAppsScriptUrl;
    
    const response = await fetch(googleAppsScriptUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        email: email || 'Not provided',
        feedback: feedback,
        type: type || 'general',
        source: source || 'specifys-ai-website'
      })
    });
    
    if (!response.ok) {
      throw new Error(`Google Apps Script error: ${response.status}`);
    }
    
    const result = await response.json();

    
  } catch (error) {

    // Don't fail the entire request if Sheets fails


      email: email || 'Not provided',
      feedback: feedback,
      type: type || 'general',
      source: source || 'specifys-ai-website',
      timestamp: new Date().toISOString()
    });
  }
}

// Endpoint for generating specifications via Cloudflare Worker
app.post('/api/generate-spec', async (req, res) => {
  const requestId = req.requestId || `req-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
  const startTime = Date.now();
  
  console.log(`[${requestId}] ===== /api/generate-spec REQUEST START (server.js) =====`);
  console.log(`[${requestId}] Timestamp: ${new Date().toISOString()}`);
  console.log(`[${requestId}] IP: ${req.ip || req.connection.remoteAddress}`);
  console.log(`[${requestId}] User-Agent: ${req.headers['user-agent'] || 'N/A'}`);
  console.log(`[${requestId}] Request Body:`, {
    hasUserInput: !!req.body.userInput,
    userInputLength: req.body.userInput?.length || 0,
    userInputPreview: req.body.userInput?.substring(0, 200) || 'N/A'
  });

  const { userInput } = req.body;

  if (!userInput) {
    console.log(`[${requestId}] ❌ VALIDATION FAILED: userInput is missing`);
    return res.status(400).json({ error: 'User input is required' });
  }

  try {
    // Convert userInput to Cloudflare Worker format
    // Worker expects: { stage: "overview", prompt: { system, developer, user } }
    const workerPayload = {
      stage: 'overview',
      locale: 'en-US',
      prompt: {
        system: 'You are an expert application specification generator. Generate detailed, comprehensive specifications based on user requirements.',
        developer: 'Return ONLY valid JSON (no text/markdown). Top-level key MUST be overview. Follow the exact structure specified in the user prompt.',
        user: userInput
      }
    };

    console.log(`[${requestId}] 📤 Preparing request to Cloudflare Worker`);
    console.log(`[${requestId}] Worker URL: https://spspec.shalom-cohen-111.workers.dev/generate`);
    console.log(`[${requestId}] Worker Payload:`, {
      stage: workerPayload.stage,
      locale: workerPayload.locale,
      promptSystemLength: workerPayload.prompt.system.length,
      promptDeveloperLength: workerPayload.prompt.developer.length,
      promptUserLength: workerPayload.prompt.user.length,
      promptUserPreview: workerPayload.prompt.user.substring(0, 200)
    });

    const workerRequestStart = Date.now();

    // Forward request to Cloudflare Worker
    let response;
    try {
      console.log(`[${requestId}] 🔄 Attempting to fetch from Cloudflare Worker...`);
      response = await fetch('https://spspec.shalom-cohen-111.workers.dev/generate', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(workerPayload),
      });
      console.log(`[${requestId}] ✅ Fetch completed successfully`);
    } catch (fetchError) {
      console.error(`[${requestId}] ❌ Fetch failed:`, {
        message: fetchError.message,
        name: fetchError.name,
        stack: fetchError.stack,
        cause: fetchError.cause
      });
      throw new Error(`Failed to connect to Cloudflare Worker: ${fetchError.message}`);
    }

    const workerRequestTime = Date.now() - workerRequestStart;
    console.log(`[${requestId}] ⏱️  Worker request took ${workerRequestTime}ms`);
    console.log(`[${requestId}] 📥 Worker Response Status: ${response.status} ${response.statusText}`);
    console.log(`[${requestId}] Worker Response Headers:`, {
      'content-type': response.headers.get('content-type'),
      'content-length': response.headers.get('content-length'),
      'cf-ray': response.headers.get('cf-ray'),
      'cf-request-id': response.headers.get('cf-request-id')
    });

    // Read response body first (before checking ok) to see what Worker returned
    let responseBodyText = null;
    let responseBodyJson = null;
    try {
      responseBodyText = await response.text();
      console.log(`[${requestId}] 📄 Worker Response Body (raw, first 500 chars):`, responseBodyText.substring(0, 500));
      try {
        responseBodyJson = JSON.parse(responseBodyText);
        console.log(`[${requestId}] 📄 Worker Response Body (parsed):`, JSON.stringify(responseBodyJson, null, 2));
      } catch (jsonParseError) {
        console.log(`[${requestId}] ⚠️  Worker response is not valid JSON:`, jsonParseError.message);
      }
    } catch (readError) {
      console.error(`[${requestId}] ❌ Failed to read Worker response body:`, readError.message);
    }

    // Check if response is OK
    if (!response.ok) {
      console.log(`[${requestId}] ❌ Worker returned error status: ${response.status}`);
      let errorMessage = 'Failed to fetch specification';
      let errorDetails = null;
      
      if (responseBodyJson) {
        errorDetails = responseBodyJson;
        // Worker returns errors in format: { error: { code, message, issues? }, correlationId? }
        if (responseBodyJson.error) {
          errorMessage = responseBodyJson.error.message || responseBodyJson.error.code || errorMessage;
          if (responseBodyJson.error.issues && Array.isArray(responseBodyJson.error.issues)) {
            errorMessage += ': ' + responseBodyJson.error.issues.join(', ');
          }
          if (responseBodyJson.error.code) {
            errorMessage = `[${responseBodyJson.error.code}] ${errorMessage}`;
          }
        }
        console.log(`[${requestId}] Worker Error Data (from JSON):`, JSON.stringify(responseBodyJson, null, 2));
        if (responseBodyJson.correlationId) {
          console.log(`[${requestId}] Worker Correlation ID: ${responseBodyJson.correlationId}`);
        }
      } else if (responseBodyText) {
        errorMessage = responseBodyText.substring(0, 500) || `HTTP ${response.status}: ${response.statusText}`;
        errorDetails = { text: responseBodyText };
        console.log(`[${requestId}] Worker Error Text:`, responseBodyText.substring(0, 500));
      } else {
        errorMessage = `HTTP ${response.status}: ${response.statusText}`;
        errorDetails = { status: response.status, statusText: response.statusText };
        console.log(`[${requestId}] Worker Error (no body):`, errorMessage);
      }
      
      const totalTime = Date.now() - startTime;
      console.log(`[${requestId}] ===== /api/generate-spec REQUEST FAILED (${totalTime}ms) =====`);
      throw new Error(errorMessage);
    }

    // Response is OK, use the parsed JSON
    if (!responseBodyJson) {
      const totalTime = Date.now() - startTime;
      console.error(`[${requestId}] ❌ Worker returned OK but response is not valid JSON`);
      console.log(`[${requestId}] ===== /api/generate-spec REQUEST FAILED (${totalTime}ms) =====`);
      throw new Error('Worker returned invalid JSON response');
    }
    
    const data = responseBodyJson;
    
    console.log(`[${requestId}] ✅ Successfully received and parsed Worker response`);
    console.log(`[${requestId}] Response Structure:`, {
      hasOverview: !!data.overview,
      hasSpecification: !!data.specification,
      hasMeta: !!data.meta,
      keys: Object.keys(data),
      overviewKeys: data.overview ? Object.keys(data.overview) : null
    });
    
    // Cloudflare Worker returns { overview: {...}, meta: {...} } format
    // Convert to { specification: ... } format for backward compatibility
    let specification;
    if (data.overview) {
      // Worker returned structured data
      specification = JSON.stringify(data.overview);
      console.log(`[${requestId}] 📝 Using 'overview' field, length: ${specification.length}`);
    } else if (data.specification) {
      // Already in expected format
      specification = data.specification;
      console.log(`[${requestId}] 📝 Using 'specification' field, length: ${specification.length}`);
    } else {
      // Fallback - stringify entire response
      specification = JSON.stringify(data);
      console.log(`[${requestId}] ⚠️  Using fallback (stringify entire response), length: ${specification.length}`);
    }
    
    const totalTime = Date.now() - startTime;
    console.log(`[${requestId}] ✅ Successfully generated specification (${totalTime}ms total)`);
    console.log(`[${requestId}] ===== /api/generate-spec REQUEST SUCCESS =====`);
    
    res.json({ specification });
  } catch (error) {
    const totalTime = Date.now() - startTime;
    console.error(`[${requestId}] ❌ ERROR in /api/generate-spec (${totalTime}ms):`, {
      message: error.message,
      stack: error.stack,
      name: error.name,
      cause: error.cause
    });
    console.error(`[${requestId}] ===== /api/generate-spec REQUEST ERROR =====`);
    
    // Always include error details in response for debugging
    res.status(500).json({ 
      error: 'Failed to generate specification',
      details: error.message,
      errorType: error.name,
      requestId: requestId
    });
  }
});

// Repair diagram endpoint (legacy - kept for backward compatibility)
app.post('/api/diagrams/repair', async (req, res) => {

  
  const { overview, technical, market, diagramTitle, brokenDiagramCode } = req.body;
  
  if (!brokenDiagramCode) {
    return res.status(400).json({ error: 'Broken diagram code is required' });
  }
  
  try {
    const OpenAI = require('openai');
    const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
    
    // Build context from spec
    const specContext = `
## Specification Context:
${overview ? `**Overview:**\n${overview}\n\n` : ''}
${technical ? `**Technical Specs:**\n${technical}\n\n` : ''}
${market ? `**Market Research:**\n${market}\n\n` : ''}
`;
    
    // Create a prompt to repair the diagram
    const systemPrompt = `You are a Mermaid diagram expert. Your task is to fix broken Mermaid diagrams.

When given a broken Mermaid diagram code, analyze it and create a corrected version that:
1. Follows proper Mermaid syntax
2. Accurately represents the information from the specification context provided
3. Is complete and renderable

Return ONLY valid Mermaid code, nothing else.`;
    
    const userPrompt = `The following Mermaid diagram is broken:\n\n\`\`\`mermaid\n${brokenDiagramCode}\n\`\`\`\n\nContext:\n${specContext}\n\nTitle: ${diagramTitle}\n\nPlease provide a corrected version of this diagram.`;
    
    const completion = await openai.chat.completions.create({
      model: 'gpt-4o-mini',
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: userPrompt }
      ],
      temperature: 0.3,
      max_tokens: 2000
    });
    
    const repairedCode = completion.choices[0].message.content.trim();
    
    // Clean up the response (remove any markdown code blocks)
    let cleanedCode = repairedCode;
    if (repairedCode.startsWith('```mermaid')) {
      cleanedCode = repairedCode.replace(/```mermaid\n?/, '').replace(/```\n?$/, '').trim();
    } else if (repairedCode.startsWith('```')) {
      cleanedCode = repairedCode.replace(/```\n?/, '').replace(/```\n?$/, '').trim();
    }
    

    res.json({ 
      success: true,
      repairedDiagram: {
        mermaidCode: cleanedCode
      }
    });
    
  } catch (error) {

    res.status(500).json({ error: 'Failed to repair diagram' });
  }
});

// Import and mount chat routes
const chatRoutes = require('./chat-routes');
app.use('/api/chat', chatRoutes);

// Import and mount user routes
const userRoutes = require('./user-routes');
app.use('/api/users', userRoutes);

// Import and mount specs routes
const specsRoutes = require('./specs-routes');
app.use('/api/specs', specsRoutes);

// Import and mount stats routes
const statsRoutes = require('./stats-routes');
app.use('/api/stats', statsRoutes);

// Import error logger
const { logError, getErrorLogs, getErrorSummary } = require('./error-logger');

// Import CSS crash logger
const { logCSCCrash, getCSCCrashLogs, getCSCCrashSummary } = require('./css-crash-logger');

// Admin error logs endpoint
app.get('/api/admin/error-logs', async (req, res) => {
  try {
    const limit = parseInt(req.query.limit) || 100;
    const errorType = req.query.errorType || null;
    
    const logs = await getErrorLogs(limit, errorType);
    
    res.json({ 
      success: true, 
      logs: logs,
      total: logs.length
    });
  } catch (error) {

    res.status(500).json({ error: 'Failed to get error logs' });
  }
});

// CSS crash logs endpoint - POST to receive logs
app.post('/api/admin/css-crash-logs', async (req, res) => {
  try {
    const { log, pageInfo } = req.body;
    
    if (!log || !log.crashType) {
      return res.status(400).json({ error: 'Invalid crash log data' });
    }
    
    await logCSCCrash(log);
    
    res.json({ 
      success: true, 
      message: 'CSS crash log saved' 
    });
  } catch (error) {

    res.status(500).json({ error: 'Failed to save CSS crash log' });
  }
});

// CSS crash logs endpoint - GET to retrieve logs
app.get('/api/admin/css-crash-logs', async (req, res) => {
  try {
    const limit = parseInt(req.query.limit) || 100;
    const crashType = req.query.crashType || null;
    const url = req.query.url || null;
    
    const logs = await getCSCCrashLogs(limit, crashType, url);
    
    res.json({ 
      success: true, 
      logs: logs,
      total: logs.length
    });
  } catch (error) {

    res.status(500).json({ error: 'Failed to get CSS crash logs' });
  }
});

// CSS crash summary endpoint
app.get('/api/admin/css-crash-summary', async (req, res) => {
  try {
    const summary = await getCSCCrashSummary();
    
    res.json({ 
      success: true, 
      summary: summary
    });
  } catch (error) {

    res.status(500).json({ error: 'Failed to get CSS crash summary' });
  }
});

// Error summary endpoint
app.get('/api/admin/error-summary', async (req, res) => {
  try {
    const summary = await getErrorSummary();
    
    res.json({ 
      success: true, 
      summary: summary 
    });
  } catch (error) {

    res.status(500).json({ error: 'Failed to get error summary' });
  }
});


app.listen(port, () => {
  console.log('='.repeat(60));
  console.log('🚀 SERVER STARTED SUCCESSFULLY (server/server.js)');
  console.log('='.repeat(60));
  console.log(`📅 Timestamp: ${new Date().toISOString()}`);
  console.log(`🌐 Port: ${port}`);
  console.log(`🖥️  Node.js: ${process.version}`);
  console.log(`📁 Environment: ${process.env.NODE_ENV || 'development'}`);
  console.log(`🔧 OpenAI API Key: ${process.env.OPENAI_API_KEY ? '✅ Configured' : '❌ Not configured'}`);
  console.log(`☁️  Cloudflare Worker: https://spspec.shalom-cohen-111.workers.dev/generate`);
  console.log('='.repeat(60));
  console.log('📝 Logging enabled for all API requests');
  console.log('📊 Detailed logs for /api/generate-spec endpoint');
  console.log('='.repeat(60));
  
  // Check configuration
  if (!process.env.EMAIL_USER || !process.env.EMAIL_APP_PASSWORD) {
    console.log('⚠️  Email configuration not found (EMAIL_USER, EMAIL_APP_PASSWORD)');
  } else {
    console.log('✅ Email configuration found');
  }
  
  if (!process.env.GOOGLE_SHEETS_WEBHOOK_URL) {
    console.log('⚠️  Google Sheets webhook URL not configured');
  } else {
    console.log('✅ Google Sheets webhook URL configured');
  }
}).on('error', (err) => {
  console.error('='.repeat(60));
  console.error('❌ FAILED TO START SERVER (server/server.js)');
  console.error('='.repeat(60));
  console.error(`Error: ${err.message}`);
  console.error(`Code: ${err.code}`);
  console.error(`Stack: ${err.stack}`);
  console.error('='.repeat(60));
});
