const express = require('express');
const fetch = require('node-fetch');
const dotenv = require('dotenv');
const config = require('./config');

dotenv.config();

const app = express();
const port = config.port;

// Middleware to parse JSON bodies
app.use(express.json());

// CORS middleware to allow requests from your frontend
app.use((req, res, next) => {
  const origin = req.headers.origin;
  
  // Check if origin is in allowed list
  if (origin && config.allowedOrigins.includes(origin)) {
    res.header('Access-Control-Allow-Origin', origin);
  } else {
    res.header('Access-Control-Allow-Origin', '*'); // Fallback for development
  }
  
  res.header('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept, Authorization');
  res.header('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS');
  
  // Handle preflight requests
  if (req.method === 'OPTIONS') {
    res.sendStatus(200);
  } else {
    next();
  }
});

// Feedback endpoint
app.post('/api/feedback', async (req, res) => {
  const { email, feedback, type, source } = req.body;

  if (!feedback) {
    return res.status(400).json({ error: 'Feedback text is required' });
  }

  try {
    // 1. Send email notification
    await sendFeedbackEmail(email, feedback);
    
    // 2. Save to Google Sheets via Google Apps Script
    await saveToGoogleSheets(email, feedback, type, source);
    
    res.json({ success: true, message: 'Feedback submitted successfully' });
  } catch (error) {

    res.status(500).json({ error: 'Failed to process feedback' });
  }
});

// Function to send feedback email
async function sendFeedbackEmail(email, feedback) {
  try {
    // Check if email configuration is available
    const emailUser = process.env.EMAIL_USER;
    const emailPassword = process.env.EMAIL_APP_PASSWORD;
    const feedbackEmail = process.env.FEEDBACK_EMAIL;
    
    if (emailUser && emailPassword && feedbackEmail) {
      // Use Nodemailer to send email
      const nodemailer = require('nodemailer');
      
      const transporter = nodemailer.createTransporter({
        service: 'gmail',
        auth: {
          user: emailUser,
          pass: emailPassword
        }
      });
      
      const mailOptions = {
        from: emailUser,
        to: feedbackEmail,
        subject: 'New Feedback from Specifys.ai',
        html: `
          <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
            <h2 style="color: #0078d4;">📝 New Feedback Received</h2>
            <div style="background: #f5f5f5; padding: 20px; border-radius: 8px; margin: 20px 0;">
              <p><strong>📧 User Email:</strong> ${email || 'Not provided'}</p>
              <p><strong>🕒 Time:</strong> ${new Date().toLocaleString('he-IL', { timeZone: 'Asia/Jerusalem' })}</p>
              <p><strong>📱 Source:</strong> Specifys.ai Try Page</p>
            </div>
            <div style="background: #fff; padding: 20px; border-left: 4px solid #0078d4; margin: 20px 0;">
              <h3 style="color: #333; margin-top: 0;">Feedback Content:</h3>
              <p style="color: #555; line-height: 1.6; white-space: pre-wrap;">${feedback}</p>
            </div>
            <hr style="border: none; border-top: 1px solid #eee; margin: 20px 0;">
            <p style="color: #666; font-size: 12px;">This email was automatically generated by the Specifys.ai feedback system.</p>
          </div>
        `
      };
      
      const info = await transporter.sendMail(mailOptions);
      
    } else {
      // Fallback: log to console
    }
    
  } catch (error) {

    // Don't fail the entire request if email fails
  }
}

// Function to save feedback to Google Sheets via Google Apps Script
async function saveToGoogleSheets(email, feedback, type, source) {
  try {
    // Use the Google Apps Script URL from config
    const googleAppsScriptUrl = config.googleAppsScriptUrl;
    
    const response = await fetch(googleAppsScriptUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        email: email || 'Not provided',
        feedback: feedback,
        type: type || 'general',
        source: source || 'specifys-ai-website'
      })
    });
    
    if (!response.ok) {
      throw new Error(`Google Apps Script error: ${response.status}`);
    }
    
    const result = await response.json();

    
  } catch (error) {

    // Don't fail the entire request if Sheets fails


      email: email || 'Not provided',
      feedback: feedback,
      type: type || 'general',
      source: source || 'specifys-ai-website',
      timestamp: new Date().toISOString()
    });
  }
}

// Clean API endpoint for generating specifications
app.post('/api/generate-spec', async (req, res) => {

  const { userInput } = req.body;

  if (!userInput) {

    return res.status(400).json({ error: 'User input is required' });
  }

  try {
    // Forward request to the existing Cloudflare Worker
    const response = await fetch('https://newnocode.shalom-cohen-111.workers.dev', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ prompt: userInput }),
    });

    const data = await response.json();
    if (!response.ok) {

      throw new Error(data.error?.message || 'Failed to fetch specification');
    }


    res.json({ specification: data.specification || 'No specification generated' });
  } catch (error) {

    res.status(500).json({ error: 'Failed to generate specification' });
  }
});

// Repair diagram endpoint (legacy - kept for backward compatibility)
app.post('/api/diagrams/repair', async (req, res) => {

  
  const { overview, technical, market, diagramTitle, brokenDiagramCode } = req.body;
  
  if (!brokenDiagramCode) {
    return res.status(400).json({ error: 'Broken diagram code is required' });
  }
  
  try {
    const OpenAI = require('openai');
    const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
    
    // Build context from spec
    const specContext = `
## Specification Context:
${overview ? `**Overview:**\n${overview}\n\n` : ''}
${technical ? `**Technical Specs:**\n${technical}\n\n` : ''}
${market ? `**Market Research:**\n${market}\n\n` : ''}
`;
    
    // Create a prompt to repair the diagram
    const systemPrompt = `You are a Mermaid diagram expert. Your task is to fix broken Mermaid diagrams.

When given a broken Mermaid diagram code, analyze it and create a corrected version that:
1. Follows proper Mermaid syntax
2. Accurately represents the information from the specification context provided
3. Is complete and renderable

Return ONLY valid Mermaid code, nothing else.`;
    
    const userPrompt = `The following Mermaid diagram is broken:\n\n\`\`\`mermaid\n${brokenDiagramCode}\n\`\`\`\n\nContext:\n${specContext}\n\nTitle: ${diagramTitle}\n\nPlease provide a corrected version of this diagram.`;
    
    const completion = await openai.chat.completions.create({
      model: 'gpt-4o-mini',
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: userPrompt }
      ],
      temperature: 0.3,
      max_tokens: 2000
    });
    
    const repairedCode = completion.choices[0].message.content.trim();
    
    // Clean up the response (remove any markdown code blocks)
    let cleanedCode = repairedCode;
    if (repairedCode.startsWith('```mermaid')) {
      cleanedCode = repairedCode.replace(/```mermaid\n?/, '').replace(/```\n?$/, '').trim();
    } else if (repairedCode.startsWith('```')) {
      cleanedCode = repairedCode.replace(/```\n?/, '').replace(/```\n?$/, '').trim();
    }
    

    res.json({ 
      success: true,
      repairedDiagram: {
        mermaidCode: cleanedCode
      }
    });
    
  } catch (error) {

    res.status(500).json({ error: 'Failed to repair diagram' });
  }
});

// Import and mount chat routes
const chatRoutes = require('./chat-routes');
app.use('/api/chat', chatRoutes);

// Import and mount user routes
const userRoutes = require('./user-routes');
app.use('/api/users', userRoutes);

// Import and mount stats routes
const statsRoutes = require('./stats-routes');
app.use('/api/stats', statsRoutes);

// Import error logger
const { logError, getErrorLogs, getErrorSummary } = require('./error-logger');

// Import CSS crash logger
const { logCSCCrash, getCSCCrashLogs, getCSCCrashSummary } = require('./css-crash-logger');

// Admin error logs endpoint
app.get('/api/admin/error-logs', async (req, res) => {
  try {
    const limit = parseInt(req.query.limit) || 100;
    const errorType = req.query.errorType || null;
    
    const logs = await getErrorLogs(limit, errorType);
    
    res.json({ 
      success: true, 
      logs: logs,
      total: logs.length
    });
  } catch (error) {

    res.status(500).json({ error: 'Failed to get error logs' });
  }
});

// CSS crash logs endpoint - POST to receive logs
app.post('/api/admin/css-crash-logs', async (req, res) => {
  try {
    const { log, pageInfo } = req.body;
    
    if (!log || !log.crashType) {
      return res.status(400).json({ error: 'Invalid crash log data' });
    }
    
    await logCSCCrash(log);
    
    res.json({ 
      success: true, 
      message: 'CSS crash log saved' 
    });
  } catch (error) {

    res.status(500).json({ error: 'Failed to save CSS crash log' });
  }
});

// CSS crash logs endpoint - GET to retrieve logs
app.get('/api/admin/css-crash-logs', async (req, res) => {
  try {
    const limit = parseInt(req.query.limit) || 100;
    const crashType = req.query.crashType || null;
    const url = req.query.url || null;
    
    const logs = await getCSCCrashLogs(limit, crashType, url);
    
    res.json({ 
      success: true, 
      logs: logs,
      total: logs.length
    });
  } catch (error) {

    res.status(500).json({ error: 'Failed to get CSS crash logs' });
  }
});

// CSS crash summary endpoint
app.get('/api/admin/css-crash-summary', async (req, res) => {
  try {
    const summary = await getCSCCrashSummary();
    
    res.json({ 
      success: true, 
      summary: summary
    });
  } catch (error) {

    res.status(500).json({ error: 'Failed to get CSS crash summary' });
  }
});

// Error summary endpoint
app.get('/api/admin/error-summary', async (req, res) => {
  try {
    const summary = await getErrorSummary();
    
    res.json({ 
      success: true, 
      summary: summary 
    });
  } catch (error) {

    res.status(500).json({ error: 'Failed to get error summary' });
  }
});


app.listen(port, () => {




  
  // Check configuration
  if (!process.env.EMAIL_USER || !process.env.EMAIL_APP_PASSWORD) {

  }
  
  if (!process.env.GOOGLE_SHEETS_WEBHOOK_URL) {

  }
});
