#!/usr/bin/env node
/**
 * generate-favicon.mjs
 *
 * Rebuilds the entire favicon set from a single source SVG so that every
 * generated PNG/ICO has a *transparent* background outside the orange squircle.
 *
 * Outputs (relative to repo root):
 *   /favicon.svg                              ← modern browsers (Chrome, FF, Safari 12+, Edge)
 *   /favicon.ico                              ← legacy fallback, multi-resolution (16, 32, 48, 64)
 *   /assets/images/icon-192.png               ← Android home screen / webmanifest
 *   /assets/images/icon-512.png               ← Android home screen / webmanifest
 *   /assets/images/apple-touch-icon.png       ← iOS home screen (180×180)
 *   /assets/images/favicon-32.png             ← extra: explicit 32px sometimes referenced
 *   /assets/images/favicon-16.png             ← extra: explicit 16px sometimes referenced
 *
 * The SVG is identical to the icon-mark generated by the admin Brand Kit page
 * (`assets/js/new-admin-dashboard/views/BrandView.js → buildIconMarkSvg`).
 *
 * Run from the repo root:
 *   node scripts/generate-favicon.mjs
 */

import { Resvg } from '@resvg/resvg-js';
import pngToIco from 'png-to-ico';
import { writeFile, mkdir } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, '..');

// Brand palette (must match assets/css/core/_variables.scss)
const ORANGE = '#FF6B35';
const WHITE  = '#FFFFFF';

/**
 * Source SVG. Same construction as BrandView.buildIconMarkSvg with bg=orange.
 * Critically, there's *no* outer `<rect>` outside the rounded square — the corners
 * of the viewBox are transparent, which is exactly what fixes the user's bug.
 */
function buildIconSvg({ widthAttr = 512, fg = WHITE, bg = ORANGE } = {}) {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" width="${widthAttr}" height="${widthAttr}" preserveAspectRatio="xMidYMid meet">
  <rect width="100" height="100" rx="22" ry="22" fill="${bg}"/>
  <text x="50" y="52" text-anchor="middle" dominant-baseline="central"
        font-family="'Inter', 'Montserrat', -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif"
        font-size="78" font-weight="900" letter-spacing="-3" fill="${fg}">S</text>
</svg>`;
}

/**
 * Rasterize the source SVG to a PNG Buffer at exact `size` × `size` pixels.
 * resvg picks Helvetica/system fonts automatically when Inter isn't installed —
 * the visual result is still a clean bold S filling the squircle.
 */
function rasterize(svg, size) {
  const resvg = new Resvg(svg, {
    background: 'rgba(0, 0, 0, 0)', // transparent
    fitTo: { mode: 'width', value: size },
    font: {
      // Allow loading any system font; default sans-serif is fine for "S"
      loadSystemFonts: true,
      defaultFontFamily: 'Helvetica'
    }
  });
  return resvg.render().asPng();
}

async function writeAndLog(path, buffer, label) {
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, buffer);
  console.log(`✔ ${label.padEnd(28)} ${(buffer.length / 1024).toFixed(1).padStart(8)} KB → ${path.replace(REPO_ROOT + '/', '')}`);
}

async function main() {
  console.log('Generating favicon assets from a single transparent-corner SVG…\n');

  // 1. The SVG itself
  const svgString = buildIconSvg({ widthAttr: 100 });
  await writeAndLog(resolve(REPO_ROOT, 'favicon.svg'), Buffer.from(svgString, 'utf8'), 'favicon.svg (vector)');

  // 2. PNG renders at standard favicon / app-icon sizes
  //    The SVG we hand to resvg is sized 1024 → resvg rescales to the target.
  const sourceForRaster = buildIconSvg({ widthAttr: 1024 });

  const sizes = [
    { size: 16,  out: 'assets/images/favicon-16.png',         label: 'favicon-16.png' },
    { size: 32,  out: 'assets/images/favicon-32.png',         label: 'favicon-32.png' },
    { size: 48,  out: 'assets/images/favicon-48.png',         label: 'favicon-48.png' },
    { size: 64,  out: 'assets/images/favicon-64.png',         label: 'favicon-64.png' },
    { size: 180, out: 'assets/images/apple-touch-icon.png',   label: 'apple-touch-icon.png (180×180)' },
    { size: 192, out: 'assets/images/icon-192.png',           label: 'icon-192.png (PWA)' },
    { size: 512, out: 'assets/images/icon-512.png',           label: 'icon-512.png (PWA)' }
  ];

  const pngBuffers = {};
  for (const { size, out, label } of sizes) {
    const buf = rasterize(sourceForRaster, size);
    pngBuffers[size] = buf;
    await writeAndLog(resolve(REPO_ROOT, out), buf, label);
  }

  // 3. favicon.ico (multi-resolution: 16, 32, 48, 64)
  //    Legacy browsers and Windows tooling still pick this up.
  const icoBuffer = await pngToIco([
    pngBuffers[16],
    pngBuffers[32],
    pngBuffers[48],
    pngBuffers[64]
  ]);
  await writeAndLog(resolve(REPO_ROOT, 'favicon.ico'), icoBuffer, 'favicon.ico (multi-res)');

  console.log('\nDone. Hard-refresh the browser (Cmd-Shift-R) to flush the cached old favicon.');
}

main().catch(err => {
  console.error('Favicon generation failed:', err);
  process.exit(1);
});
